[project]
name = "podcast-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.8.1",
    "youtube-transcript-api>=1.0.3",
]
